### ISSUE TITLE
Back button not work or can't exit using back button

### ISSUE THREAD

**Issue by muhammadarif1** [NearbyShops/Nearby-Shops-Android-app#12]

**Comment by muhammadarif1** [comment]
@SumeetMoray

**Comment by SumeetMoray** [comment]
can you tell the phone model and android version where you are facing this issue ?

**Comment by muhammadarif1** [comment]
android 5.1 
device model oppo neo 5

**Comment by muhammadarif1** [comment]
@SumeetMoray are you able to find the error?

**Comment by SumeetMoray** [comment]
i dont have oppo devices ... but its working fine on other devices ... and android version 8 and above ... 

it could be the device manufacturer disabled the back button overriding ... feature ... but try to check this for oppo with android version 8 and above ...

If it works fine we can ignore this issue because not many people will use 5.1 its quite old !
