### ISSUE TITLE
Migration to 'NearbyShops' organization?

### ISSUE THREAD

**Issue by jayaddison** [NearbyShops/Nearby-Shops-Android-app#17]
Hi @SumeetMoray - great to see that the code for the Nearby Shops Android app is now open.

I wondered if it would make sense to migrate this into the [NearbyShops GitHub org](https://github.com/NearbyShops) or whether you have plans to keep this separate?

**Comment by SumeetMoray** [comment]
Hi I am facing quite a  dilemma ...

I want to keep this project open source. So that people can benefit from it. 

But have you heard news about how startups like Instacart and Amazon have been abusing gig workers. 

https://medium.com/@GigWorkersCollective/instacart-emergency-walk-off-ebdf11b6995a


I don't want someone to use this project to build another startup that abuse people like the Instacart does.  

Is there anyway I can prevent such misuse of this technology ??

**Comment by jayaddison** [comment]
@SumeetMoray Very good question.  All my opinion, but I'll try:

Those companies are acting in a relatively predictable way, by marketing the positive services they provide during any particular circumstances.  There's little reason for them to highlight the problems that they cause or ignore.

Fortunately, we can all spread information about what's happening (as you just did, for example) and based on what we read individually, we can decide on the services we want to use for food delivery.

To avoid misuse of technology, we have to assume that most of the world will remain open to sharing and communicating, and that the majority of those people will understand the [golden rule](https://en.wikipedia.org/wiki/Golden_Rule) and that they should support and create environments that they would be comfortable in themselves.

In an economic market, one of the most powerful decisions that groups of customers can make is to choose their preferred vendor(s).  If companies see that they're losing customers as a result of a shift in demand, then they should react by addressing the customer's reasons for moving -- or they will fall behind.

Our task (or our choice) is to build what we feel are preferable alternatives to existing structures -- and to be transparent and take community input.

It's also important to keep listening to users and to local regulations.  We should try our best to avoid any negative impact on customers (even when most of the service provided is positive), and to address any problems that occur thoughtfully and carefully.

Consumers can only a trust a company based on what they read about and see it doing, and open systems have inherent advantages there.  It's easier to inspect the code, and even if people attempt to spread misinformation about our software, we can provide code and commit references to indicate the truth.

In the short term, opaque businesses may have some advantages thanks to having (sometimes hidden) relationships with supply chains, and proprietary software based on internal knowledge.  But neither of those could not equally be developed in the open, given enough planning, trust, review and maintenance.

**Comment by SumeetMoray** [comment]
@jayaddison 

Thank you ... I had been dealing this all alone and having supporting words from you is really helpful ! Your interest and willingness to help and support resolve this issue further restores my faith in the Open-Source and collaberative development. 

You are right when you say. In the economy the people have the freedom to decide and vote for the service. Just like we vote for our politicians we can vote for services also. And ultimately people can choose the best service providers who provide better service and provide good treatment to their employees. 

Therefore i believe its good to keep things open source. Because when we keep things open we are also empowering the good people and good forces who want to do good in the society. 

In fact open-source software is the great way to help overcome abuse of gig-workers and other such kind of abuses. 

Offcourse there would be people who may want to misuse this technology. But there will be people who want to use it for good purpose also ! 

You are also right when you say open-source promotes data transparency. Our algorithms are transparent therefore we cant manipulate them and this is something that people will liike !

Lets hope for the best and Keep faith !

**Comment by jayaddison** [comment]
@SumeetMoray Thanks for the invitation to `NearbyShops`!

You're on a good path - note that we can't guarantee that open & libre source software will solve the problems gig workers experience, but it can provide more choice, transparency, and accountability -- and we can choose to build it in a way that improves everyone's outcomes.

While I consider whether I can accept your invitation at the moment - could I ask whether you have any plans for a Code of Conduct for contributors to the project?

**Comment by SumeetMoray** [comment]
@jayaddison 

Ya exactly open source can help improve transparency and thats is something thats really valuable !

Yes we will add a code of conduct for contributors ... 

...   the purpose i added you is ... if something happens to me and i die tomorrow ... This project may die with me ... Therefore we need someone who can atleast ... be a guardian of this project in case something happens to me !

You dont need to contribute code ... i mean if you want you can ... but its not necessary ...

**Comment by jayaddison** [comment]
@SumeetMoray Fortunately, GitHub (and again, open source in general) already provides backup options in case we're not able to continue contributing for any reason.

Now that your repositories are public, anyone can [fork](https://guides.github.com/activities/forking/) them and develop on them.

Maybe they'd prefer to improve the data privacy of the project, or modify an integration.  Perhaps they'd decide that one of those algorithms isn't working for their community and they'd prefer to modify it.  Or maybe they don't see feedback and changes being accepted and they decide to continue it on their own.

That's all normal and part of the process; just carry on and keep on developing the product and service you want to create, and the rest will follow.

**Comment by jayaddison** [comment]
@SumeetMoray One more comment to add - given that it's an unusual time, please make sure that you and your close family & friends are safe and comfortable before working on `NearbyShops`, or any other project.

It's a difficult time and we'll all get through it by taking care of ourselves to make sure we have all the energy we need to build services and help others.  Keep up your good work :)

**Comment by SumeetMoray** [comment]
@jayaddison 

Thanks jay ... thats kind of you to care ! ... yes i am alright ... its a little concerning the situation we are facing ... but things are alright now !

I wish the same for you also. Take care of yourself and your friends and family !
Stay safe and lets pray for everyone and humanity to get better !

**Comment by jayaddison** [comment]
Migration of the `Nearby-Shops-Android-app` repository to `NearbyShops` organization is complete, so I'll close this issue, and will join the organization at a later date when I can.  Thanks again @SumeetMoray !

**Comment by SumeetMoray** [comment]
@jayaddison 

I saw that you deleted the fork you made ... is there anything you didnt liked about this project. 
Your feedback can help me improve the project. 

Anyway, something that you may not be aware of. This repository was actually open-source since 2 years. And it also had about 560 Stars also. 

I made it private about 2 months ago. Recently i had been seeing few commercial app launches on Playstore who have used this project. This is quite painful to see other people making money using our work when we havent made even a single penny. 

Anyway, but despite all of this ... i made a decision to open-source this project again because Open - Source has helped me in many ways. And we can make money from open-source project also. 

One thing i did not like about open-source culture is exploitation of developers on the name of free and open-source. Developers deserve to be paid reasonably for their work. 

But this is something that can be fixed. So we have a policy of paying our contributors. 
Unlike other projects we dont accept free contributions unless its a minor contribution like an edit in a readme file.

**Comment by jayaddison** [comment]
@SumeetMoray Glad to see you continuing to make progress - I usually delete my forks of projects as soon as my planned commits & branches are merged.  It helps keep GitHub and the environment a bit simpler for everyone.

Stars aren't everything; some projects attract a lot of attention but might have underlying quality issues - and other projects might be very good but take time to attract attention.

If you find other people copying your work and profiting from it, report it briefly to the responsible app store / hosting environment and move on; don't let people copying your code waste your time.  They can't become too popular because eventually everyone will realize they're a copy.

Good luck with open source revenue sharing, that's a good idea.  If you want to make sure the project survives for the longest time and maximizes long-term revenue for you and people involved later, my opinion is that you should put the product experience and value for users first.

**Comment by SumeetMoray** [comment]
@jayaddison Good to know about why you are delete forks. 

I totally agree with what you have said. Yes stars doesnt always co-relate with quality of the project. 
And putting user experience first is very important. This is something i learned the hard way. But now i do realize this. 

I am learning a lot from you. 

I think exploitation of developers on the name of free and open-source is a very important issue. Unless we dont address it and find some good way to fund the project. I dont see free and open-source having any true meaningful purpose / existance in society. Because its not sustainable. 

Please read this articles really good one's . I think every open-source developer should read it. 

https://www.mikeperham.com/2015/11/23/how-to-charge-for-your-open-source/

https://medium.com/@kitze/github-stars-wont-pay-your-rent-8b348e12baed

I think keeping project open-source is okay but we must arrange for some source of revenue. 
Based on the advice of Mike Perham ... I am thinking of charging users a licence fee for commercial use. 

I even have a pricing page ready : https://nearbyshops.org/pricing.html
