### ISSUE TITLE
Out of stock but still available

### ISSUE THREAD

**Issue by abajorat** [NearbyShops/Nearby-Shops-Android-app#19]
Can add an item that is out of stock to cart. Just one but nevertheless.
Maybe items should not even appear in shop when out of stock.

**Comment by SumeetMoray** [comment]
Thanks ... for pointing out ... yes i acknowledge it as a bug ... and we will have a fix !

**Comment by abajorat** [comment]
Checked on your update:
I can't add to the cart anymore, but it is still possible to select 1 out-of-stock item. But when I then add it to the cart, it does not appear in the cart.
![image](https://user-images.githubusercontent.com/7437976/80314291-3e76eb80-87b6-11ea-9f20-ac56020f9170.png)

**Comment by abajorat** [comment]
Also when I click Add on an OOS item and then minus, negative items and payment get added in the overview on the bottom.
![image](https://user-images.githubusercontent.com/7437976/80314389-fc01de80-87b6-11ea-8606-be4f71009fdb.png)

**Comment by abajorat** [comment]
I can even lower the total amount in the cart by adding negative bananas even though they do not 
appear they still have an effect on the price
Here I have Papayas for 15$ and Pomegranates for 35$ but the total is 29 because I added 7 negative bananas for 3$ each
![image](https://user-images.githubusercontent.com/7437976/80314734-da095b80-87b8-11ea-961c-7aa70b3f7176.png)

**Comment by SumeetMoray** [comment]
I fixed that bug where you were able to add out of stock item ... its fixed in the latest commit !

Well you cannot add negative items ... it is the error in calculation of the cart total on the client side ... this bug is only on the client side ... as the real value of item total is calculated on the server side therefore the actual order total is not affected by this. 

When you update your cart ... the total gets updated to the real value fetched from server ! 

Anyway, it has been fixed too. Please checkout the latest code and try again both of these bugs should be fixed !

**Comment by abajorat** [comment]
works great, thank you
