### ISSUE TITLE
Need to select delivery address when picking up from shop

### ISSUE THREAD

**Issue by abajorat** [NearbyShops/Nearby-Shops-Android-app#21]
In order placement, forced to pick delivery address even though user orders  "pick up from shop"

**Comment by SumeetMoray** [comment]
Yes that is done purposefully because ... 

Even if the customer is picking the order from the shop he still needs to provide a proper Identity, and a Name of the person who is coming for pickup. 

The Name of the person who comes for pickup can differ because you can send your friend for pickup too. Therefore we need to provide a proper identity  even of Pickup orders !
